// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTH52KErhw8h3f8_x8lwwvLKUHzzUb420',
    appId: '1:675305128458:web:e7dc8864b54b8b21c395f3',
    messagingSenderId: '675305128458',
    projectId: 'vap-uploader',
    authDomain: 'vap-uploader.firebaseapp.com',
    storageBucket: 'vap-uploader.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilRvNMNNvKKJJG8s-8_XkQeS2fMdDFsI',
    appId: '1:675305128458:android:27b42a1324813c22c395f3',
    messagingSenderId: '675305128458',
    projectId: 'vap-uploader',
    storageBucket: 'vap-uploader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMW2E4PkIfaF_yMK0mlg_brb_hKwT80GQ',
    appId: '1:675305128458:ios:8bbfa9438809c20ec395f3',
    messagingSenderId: '675305128458',
    projectId: 'vap-uploader',
    storageBucket: 'vap-uploader.firebasestorage.app',
    iosBundleId: 'com.admin.vapUploader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMW2E4PkIfaF_yMK0mlg_brb_hKwT80GQ',
    appId: '1:675305128458:ios:8bbfa9438809c20ec395f3',
    messagingSenderId: '675305128458',
    projectId: 'vap-uploader',
    storageBucket: 'vap-uploader.firebasestorage.app',
    iosBundleId: 'com.admin.vapUploader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTH52KErhw8h3f8_x8lwwvLKUHzzUb420',
    appId: '1:675305128458:web:229b80a8e1b18f56c395f3',
    messagingSenderId: '675305128458',
    projectId: 'vap-uploader',
    authDomain: 'vap-uploader.firebaseapp.com',
    storageBucket: 'vap-uploader.firebasestorage.app',
  );

}