// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGckTFp_yBW4-BqA2JsZ2MKMH2rcIpEk',
    appId: '1:473162004853:web:992c0b1549e982c44dbb3c',
    messagingSenderId: '473162004853',
    projectId: 'file-hub-da74b',
    authDomain: 'file-hub-da74b.firebaseapp.com',
    storageBucket: 'file-hub-da74b.firebasestorage.app',
    measurementId: 'G-V4TY600LM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOBWMJRgqK8AGU82m_MglP6XdW_Z3v2LQ',
    appId: '1:473162004853:android:66172b4bc3a45d824dbb3c',
    messagingSenderId: '473162004853',
    projectId: 'file-hub-da74b',
    storageBucket: 'file-hub-da74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWPvkKQwg8yGFX_0yZhEvtDbJZ5dzNfA',
    appId: '1:473162004853:ios:0a185738dfc1a1ad4dbb3c',
    messagingSenderId: '473162004853',
    projectId: 'file-hub-da74b',
    storageBucket: 'file-hub-da74b.firebasestorage.app',
    iosBundleId: 'com.raj.project.fileHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGWPvkKQwg8yGFX_0yZhEvtDbJZ5dzNfA',
    appId: '1:473162004853:ios:0a185738dfc1a1ad4dbb3c',
    messagingSenderId: '473162004853',
    projectId: 'file-hub-da74b',
    storageBucket: 'file-hub-da74b.firebasestorage.app',
    iosBundleId: 'com.raj.project.fileHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbGckTFp_yBW4-BqA2JsZ2MKMH2rcIpEk',
    appId: '1:473162004853:web:9e3a27e05fbc79134dbb3c',
    messagingSenderId: '473162004853',
    projectId: 'file-hub-da74b',
    authDomain: 'file-hub-da74b.firebaseapp.com',
    storageBucket: 'file-hub-da74b.firebasestorage.app',
    measurementId: 'G-D2V6YLXNM7',
  );
}
