name: Build and Release Flutter APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.22.3"

    - name: Install dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --split-per-abi --release --no-shrink

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Download APK artifact
      uses: actions/download-artifact@v3
      with:
        name: release-apk

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app-arm64-v8a-release.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: release-${{ steps.date.outputs.date }}
        name: "Release ${{ steps.date.outputs.date }}"
        body: |
          Flutter APK Release
          
          Build Date: ${{ steps.date.outputs.date }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}
        draft: false
        prerelease: true

permissions:
  contents: write
