name: Build and Release Flutter APK

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "stable"

    - name: Install dependencies
      run: flutter pub get

    - name: Build release APK
      run: flutter build apk --split-per-abi --release --no-shrink

    - name: Archive APK
      run: |
        mkdir -p release-apk
        cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk release-apk/

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: file-hub
        path: release-apk/app-arm64-v8a-release.apk

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v3
      with:
        name: file-hub

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: release-apk/app-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ github.run_number }}
        release_name: "Release v${{ github.run_number }}"
        body: "Automated release of the APK."
        draft: false
        prerelease: false
